[2025-05-02T16:55:01.484+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-02T16:55:01.504+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T16:54:50.765080+00:00 [queued]>
[2025-05-02T16:55:01.511+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T16:54:50.765080+00:00 [queued]>
[2025-05-02T16:55:01.512+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-02T16:55:01.523+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): preprocess_data> on 2025-05-02 16:54:50.765080+00:00
[2025-05-02T16:55:01.538+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=109) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-02T16:55:01.538+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'preprocess_data', 'manual__2025-05-02T16:54:50.765080+00:00', '--job-id', '61', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpkpdi8zkq']
[2025-05-02T16:55:01.540+0000] {standard_task_runner.py:63} INFO - Started process 111 to run task
[2025-05-02T16:55:01.540+0000] {standard_task_runner.py:91} INFO - Job 61: Subtask preprocess_data
[2025-05-02T16:55:01.584+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T16:54:50.765080+00:00 [running]> on host 0b0b6d30f653
[2025-05-02T16:55:01.652+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T16:54:50.765080+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T16:54:50.765080+00:00'
[2025-05-02T16:55:01.654+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-02T16:55:01.661+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-02T16:55:01.662+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/preprocess_data.py']
[2025-05-02T16:55:01.677+0000] {subprocess.py:86} INFO - Output:
[2025-05-02T16:55:04.148+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-02T16:55:04.155+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/preprocess_data.py", line 24, in <module>
[2025-05-02T16:55:04.155+0000] {subprocess.py:93} INFO -     df.to_csv('data/processed/processed_data.csv', index=False)
[2025-05-02T16:55:04.156+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
[2025-05-02T16:55:04.157+0000] {subprocess.py:93} INFO -     return DataFrameRenderer(formatter).to_csv(
[2025-05-02T16:55:04.158+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-02T16:55:04.158+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
[2025-05-02T16:55:04.159+0000] {subprocess.py:93} INFO -     csv_formatter.save()
[2025-05-02T16:55:04.160+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
[2025-05-02T16:55:04.160+0000] {subprocess.py:93} INFO -     with get_handle(
[2025-05-02T16:55:04.161+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^
[2025-05-02T16:55:04.161+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
[2025-05-02T16:55:04.161+0000] {subprocess.py:93} INFO -     check_parent_directory(str(handle))
[2025-05-02T16:55:04.162+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
[2025-05-02T16:55:04.162+0000] {subprocess.py:93} INFO -     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2025-05-02T16:55:04.163+0000] {subprocess.py:93} INFO - OSError: Cannot save file into a non-existent directory: 'data/processed'
[2025-05-02T16:55:04.719+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-02T16:55:04.733+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-02T16:55:04.815+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-02T16:55:04.824+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=preprocess_data, execution_date=20250502T165450, start_date=20250502T165501, end_date=20250502T165504
[2025-05-02T16:55:04.839+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 61 for task preprocess_data (Bash command failed. The command returned a non-zero exit code 1.; 111)
[2025-05-02T16:55:04.851+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-02T16:55:04.867+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T16:55:04.873+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
