[2025-05-02T17:14:23.638+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-02T17:14:23.656+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T17:07:35.124421+00:00 [queued]>
[2025-05-02T17:14:23.663+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T17:07:35.124421+00:00 [queued]>
[2025-05-02T17:14:23.663+0000] {taskinstance.py:2303} INFO - Starting attempt 2 of 2
[2025-05-02T17:14:23.673+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): preprocess_data> on 2025-05-02 17:07:35.124421+00:00
[2025-05-02T17:14:23.680+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=456) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-02T17:14:23.682+0000] {standard_task_runner.py:63} INFO - Started process 458 to run task
[2025-05-02T17:14:23.681+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'preprocess_data', 'manual__2025-05-02T17:07:35.124421+00:00', '--job-id', '70', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmpj1twaig6']
[2025-05-02T17:14:23.683+0000] {standard_task_runner.py:91} INFO - Job 70: Subtask preprocess_data
[2025-05-02T17:14:23.724+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T17:07:35.124421+00:00 [running]> on host 0b0b6d30f653
[2025-05-02T17:14:23.785+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T17:07:35.124421+00:00' AIRFLOW_CTX_TRY_NUMBER='2' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T17:07:35.124421+00:00'
[2025-05-02T17:14:23.788+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-02T17:14:23.793+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-02T17:14:23.794+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/preprocess_data.py']
[2025-05-02T17:14:23.806+0000] {subprocess.py:86} INFO - Output:
[2025-05-02T17:14:26.118+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-02T17:14:26.129+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/preprocess_data.py", line 26, in <module>
[2025-05-02T17:14:26.136+0000] {subprocess.py:93} INFO -     df.to_csv('data/processed/processed_data.csv', index=False)
[2025-05-02T17:14:26.137+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
[2025-05-02T17:14:26.139+0000] {subprocess.py:93} INFO -     return DataFrameRenderer(formatter).to_csv(
[2025-05-02T17:14:26.140+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-02T17:14:26.141+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
[2025-05-02T17:14:26.142+0000] {subprocess.py:93} INFO -     csv_formatter.save()
[2025-05-02T17:14:26.143+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
[2025-05-02T17:14:26.143+0000] {subprocess.py:93} INFO -     with get_handle(
[2025-05-02T17:14:26.144+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^
[2025-05-02T17:14:26.145+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
[2025-05-02T17:14:26.145+0000] {subprocess.py:93} INFO -     check_parent_directory(str(handle))
[2025-05-02T17:14:26.146+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
[2025-05-02T17:14:26.147+0000] {subprocess.py:93} INFO -     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2025-05-02T17:14:26.148+0000] {subprocess.py:93} INFO - OSError: Cannot save file into a non-existent directory: 'data/processed'
[2025-05-02T17:14:26.463+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-02T17:14:26.470+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-02T17:14:26.493+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-02T17:14:26.500+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=preprocess_data, execution_date=20250502T170735, start_date=20250502T171423, end_date=20250502T171426
[2025-05-02T17:14:26.511+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 70 for task preprocess_data (Bash command failed. The command returned a non-zero exit code 1.; 458)
[2025-05-02T17:14:26.556+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-02T17:14:26.576+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T17:14:26.578+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
