[2025-05-02T17:13:06.270+0000] {local_task_job_runner.py:120} INFO - ::group::Pre task execution logs
[2025-05-02T17:13:06.291+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=non-requeueable deps ti=<TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T17:12:58.298179+00:00 [queued]>
[2025-05-02T17:13:06.298+0000] {taskinstance.py:2073} INFO - Dependencies all met for dep_context=requeueable deps ti=<TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T17:12:58.298179+00:00 [queued]>
[2025-05-02T17:13:06.299+0000] {taskinstance.py:2303} INFO - Starting attempt 1 of 1
[2025-05-02T17:13:06.311+0000] {taskinstance.py:2327} INFO - Executing <Task(BashOperator): preprocess_data> on 2025-05-02 17:12:58.298179+00:00
[2025-05-02T17:13:06.319+0000] {warnings.py:110} WARNING - /home/***/.local/lib/python3.12/site-packages/***/task/task_runner/standard_task_runner.py:61: DeprecationWarning: This process (pid=409) is multi-threaded, use of fork() may lead to deadlocks in the child.
  pid = os.fork()

[2025-05-02T17:13:06.321+0000] {standard_task_runner.py:63} INFO - Started process 411 to run task
[2025-05-02T17:13:06.322+0000] {standard_task_runner.py:90} INFO - Running: ['***', 'tasks', 'run', 'weather_data_pipeline', 'preprocess_data', 'manual__2025-05-02T17:12:58.298179+00:00', '--job-id', '68', '--raw', '--subdir', 'DAGS_FOLDER/weather_pipeline_dag.py', '--cfg-path', '/tmp/tmp79375e8u']
[2025-05-02T17:13:06.324+0000] {standard_task_runner.py:91} INFO - Job 68: Subtask preprocess_data
[2025-05-02T17:13:06.376+0000] {task_command.py:426} INFO - Running <TaskInstance: weather_data_pipeline.preprocess_data manual__2025-05-02T17:12:58.298179+00:00 [running]> on host 0b0b6d30f653
[2025-05-02T17:13:06.547+0000] {taskinstance.py:2644} INFO - Exporting env vars: AIRFLOW_CTX_DAG_OWNER='***' AIRFLOW_CTX_DAG_ID='weather_data_pipeline' AIRFLOW_CTX_TASK_ID='preprocess_data' AIRFLOW_CTX_EXECUTION_DATE='2025-05-02T17:12:58.298179+00:00' AIRFLOW_CTX_TRY_NUMBER='1' AIRFLOW_CTX_DAG_RUN_ID='manual__2025-05-02T17:12:58.298179+00:00'
[2025-05-02T17:13:06.550+0000] {taskinstance.py:430} INFO - ::endgroup::
[2025-05-02T17:13:06.556+0000] {subprocess.py:63} INFO - Tmp dir root location: /tmp
[2025-05-02T17:13:06.559+0000] {subprocess.py:75} INFO - Running command: ['/usr/bin/bash', '-c', 'python /opt/***/scripts/preprocess_data.py']
[2025-05-02T17:13:06.586+0000] {subprocess.py:86} INFO - Output:
[2025-05-02T17:13:09.150+0000] {subprocess.py:93} INFO - Traceback (most recent call last):
[2025-05-02T17:13:09.156+0000] {subprocess.py:93} INFO -   File "/opt/***/scripts/preprocess_data.py", line 26, in <module>
[2025-05-02T17:13:09.157+0000] {subprocess.py:93} INFO -     df.to_csv('data/processed/processed_data.csv', index=False)
[2025-05-02T17:13:09.157+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/core/generic.py", line 3902, in to_csv
[2025-05-02T17:13:09.158+0000] {subprocess.py:93} INFO -     return DataFrameRenderer(formatter).to_csv(
[2025-05-02T17:13:09.158+0000] {subprocess.py:93} INFO -            ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
[2025-05-02T17:13:09.159+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/formats/format.py", line 1152, in to_csv
[2025-05-02T17:13:09.160+0000] {subprocess.py:93} INFO -     csv_formatter.save()
[2025-05-02T17:13:09.161+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/formats/csvs.py", line 247, in save
[2025-05-02T17:13:09.161+0000] {subprocess.py:93} INFO -     with get_handle(
[2025-05-02T17:13:09.162+0000] {subprocess.py:93} INFO -          ^^^^^^^^^^^
[2025-05-02T17:13:09.162+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 739, in get_handle
[2025-05-02T17:13:09.163+0000] {subprocess.py:93} INFO -     check_parent_directory(str(handle))
[2025-05-02T17:13:09.163+0000] {subprocess.py:93} INFO -   File "/home/***/.local/lib/python3.12/site-packages/pandas/io/common.py", line 604, in check_parent_directory
[2025-05-02T17:13:09.163+0000] {subprocess.py:93} INFO -     raise OSError(rf"Cannot save file into a non-existent directory: '{parent}'")
[2025-05-02T17:13:09.164+0000] {subprocess.py:93} INFO - OSError: Cannot save file into a non-existent directory: 'data/processed'
[2025-05-02T17:13:09.578+0000] {subprocess.py:97} INFO - Command exited with return code 1
[2025-05-02T17:13:09.586+0000] {taskinstance.py:441} INFO - ::group::Post task execution logs
[2025-05-02T17:13:09.642+0000] {taskinstance.py:2890} ERROR - Task failed with exception
Traceback (most recent call last):
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 465, in _execute_task
    result = _execute_callable(context=context, **execute_callable_kwargs)
             ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/taskinstance.py", line 432, in _execute_callable
    return execute_callable(context=context, **execute_callable_kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/models/baseoperator.py", line 400, in wrapper
    return func(self, *args, **kwargs)
           ^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "/home/airflow/.local/lib/python3.12/site-packages/airflow/operators/bash.py", line 243, in execute
    raise AirflowException(
airflow.exceptions.AirflowException: Bash command failed. The command returned a non-zero exit code 1.
[2025-05-02T17:13:09.652+0000] {taskinstance.py:1205} INFO - Marking task as FAILED. dag_id=weather_data_pipeline, task_id=preprocess_data, execution_date=20250502T171258, start_date=20250502T171306, end_date=20250502T171309
[2025-05-02T17:13:09.668+0000] {standard_task_runner.py:110} ERROR - Failed to execute job 68 for task preprocess_data (Bash command failed. The command returned a non-zero exit code 1.; 411)
[2025-05-02T17:13:09.716+0000] {local_task_job_runner.py:240} INFO - Task exited with return code 1
[2025-05-02T17:13:09.735+0000] {taskinstance.py:3482} INFO - 0 downstream tasks scheduled from follow-on schedule check
[2025-05-02T17:13:09.737+0000] {local_task_job_runner.py:222} INFO - ::endgroup::
